### ISSUE TITLE
Unhandled exception of type 'System.AccessViolationException' occurred in Scintilla.NET.dll

### ISSUE THREAD

**Issue by RudgarV** [VPKSoft/ScintillaNET#17]
I get this exception in" VisualStudio 2015" and a crash in "Visual Studio 2022" after changing the property "RightToLeft" (Me.Scintilla1.RightToLeft = System.Windows.Forms.RightToLeft.Yes).

In Windows EventViewer i get these entries:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
at ScintillaNET.Scintilla.DirectMessage(IntPtr, Int32, IntPtr, IntPtr)
at ScintillaNET.Scintilla.DirectMessage(Int32, IntPtr, IntPtr)
at ScintillaNET.Scintilla.DirectMessage(Int32, IntPtr)
at ScintillaNET.Scintilla.InitDocument(ScintillaNET.Eol, Boolean, Int32, Int32)
at ScintillaNET.Scintilla.OnHandleCreated(System.EventArgs)
at System.Windows.Forms.Control.WmCreate(System.Windows.Forms.Message ByRef)
at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
at ScintillaNET.Scintilla.WndProc(System.Windows.Forms.Message ByRef)
at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)
at System.Windows.Forms.Design.ControlDesigner+DesignerWindowTarget.DefWndProc(System.Windows.Forms.Message ByRef)
at System.Windows.Forms.Design.ControlDesigner.WndProc(System.Windows.Forms.Message ByRef)
at System.Windows.Forms.Design.ControlDesigner+DesignerWindowTarget.OnMessage(System.Windows.Forms.Message ByRef)
at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr)

Name der fehlerhaften Anwendung: devenv.exe, Version: 14.0.25420.1, Zeitstempel: 0x57685d85
Name des fehlerhaften Moduls: unknown, Version: 0.0.0.0, Zeitstempel: 0x00000000
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0000016a
ID des fehlerhaften Prozesses: 0x3af8
Startzeit der fehlerhaften Anwendung: 0x01d84fc6e411fb12
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Pfad des fehlerhaften Moduls: unknown
Berichtskennung: 2b4225c9-eb61-447d-8e05-6a952d6fdb6f
Vollständiger Name des fehlerhaften Pakets:
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by VPKSoft** [comment]
Closed due inactivity.
